name: smart_team
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  visibility_detector: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/img/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat.ttf
        - asset: assets/font/Montserrat-Italic.ttf
          weight: 700
